#
# Simulate a series of waves on a surfaced glider
#

depth: 200 # Water depth in meters where the glider is
duration: 600 # Observation length in seconds
samplingRate: 10 # Number of observations per second

gliderDepth: 0.02 # glider's center of buoyancy depth when at the surface in m

# True to Magnetic
# From https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#igrfwmm
# for 45N 125W at sea level on 2001-03-04 using the WMM model

magDeclination: 15.2947 # Degrees eastward
magInclination: 66.4238 # Degrees downwards

# MEMs sensor noise
sensor:
        accelerometer:
                noise: 120 # microg/sqrt(Hertz)
                bias:   30 # microg
        gyro:
                noise: 0.007 # degree/sec/sqrt(Hertz)
                bias:  10 # degrees/hour

# wave trains
waves:
        - name: "wind0"
          amplitude: 0.5 # Meters (1/2 wave height, i.e. amplitude of sine wave)
          heading: -45 # Degrees
          period: 5 # Seconds
          amplitudeSigma: 0.1 # Normal noise in meters of amplitude
          headingSigma: 1. # Normal noise in degrees of heading, wave to wave
          periodSigma: 0.01 # Normal noise in seconds of period, wave to wave

        - name: "swell1"
          amplitude: 2 # Meters (1/2 wave height, i.e. amplitude of sine wave)
          heading: 45 # Degrees
          period: 12 # Seconds
          amplitudeSigma: 0.5 # Normal noise in meters of amplitude
          headingSigma: 1. # Normal noise in degrees of heading, wave to wave
          periodSigma: 0.1 # Normal noise in seconds of period, wave to wave
